import React from "react";
import { api } from "../../api/client";
import { BrandLogo, defaultConfiguration } from "../../branding/BrandContext";
import { DataTable, Empty, JsonEditor, Notice, PageHeader, Spinner, dateTime, money, useLoader } from "./AdminShared";

export function DashboardPage() {
  const dashboard = useLoader(() => api.adminDashboard(), []);
  const notifications = useLoader(() => api.adminNotifications(), []);
  if (dashboard.loading) return <Spinner />;
  const acknowledge = id => api.acknowledgeNotification(id).then(notifications.refresh);
  return <><PageHeader eyebrow={new Intl.DateTimeFormat(undefined, { dateStyle: "full" }).format(new Date())} title="Dashboard" actions={<button className="button" onClick={() => { dashboard.refresh(); notifications.refresh(); }}>Refresh</button>} /><Notice type="error">{dashboard.error}</Notice>
    <section className="metric-grid">{(dashboard.data?.metrics || []).map(metric => <article className="metric" key={metric.label}><span>{metric.label}</span><strong>{metric.label === "Revenue" ? money(metric.value) : metric.value}</strong></article>)}</section>
    <div className="admin-grid"><section className="admin-card"><div className="card-heading"><h2>Recent participants</h2></div><DataTable columns={["Participant", "Assessment", "Progress", "Payment", "Last activity"]} rows={(dashboard.data?.participants || []).map(row => [<><strong>{row.name}</strong><span>{row.email}</span></>, row.track, `${row.progress || 0}%`, row.payment || row.paymentStatus || "Free", dateTime(row.activity || row.lastActivityAt)])} /></section>
      <aside className="admin-card"><div className="card-heading"><h2>System attention</h2></div><dl className="admin-definition"><div><dt>Failed emails</dt><dd>{dashboard.data?.failures?.failedEmails || 0}</dd></div><div><dt>Failed webhooks</dt><dd>{dashboard.data?.failures?.failedWebhooks || 0}</dd></div><div><dt>Critical alerts</dt><dd>{dashboard.data?.failures?.criticalAlerts || 0}</dd></div></dl><h2>Unacknowledged alerts</h2><div className="admin-list">{(notifications.data?.items || []).filter(item => !item.acknowledged_at).slice(0, 8).map(item => <div key={item.id}><strong>{item.title}</strong><small>{item.message}</small><button onClick={() => acknowledge(item.id)}>Acknowledge</button></div>)}</div></aside>
    </div></>;
}

export function ParticipantsPage() {
  const [query, setQuery] = React.useState({ search: "", status: "", track: "", page: 1, limit: 25 });
  const [selected, setSelected] = React.useState(null);
  const [notice, setNotice] = React.useState("");
  const loader = useLoader(() => api.adminParticipants(query), [query.search, query.status, query.track, query.page]);
  const open = item => api.adminParticipant(item.id).then(setSelected).catch(error => setNotice(error.message));
  const exportRecord = () => api.exportParticipant(selected.participant.id).then(data => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `participant-${selected.participant.id}.json`; link.click(); URL.revokeObjectURL(link.href); });
  const anonymise = async () => { if (!confirm("Anonymise this participant and remove direct personal identifiers?")) return; await api.anonymiseParticipant(selected.participant.id); setSelected(null); loader.refresh(); };
  return <><PageHeader title="Participants" actions={<button className="button" onClick={loader.refresh}>Refresh</button>} /><Notice type="error">{loader.error || notice}</Notice>
    <div className="admin-filters"><input placeholder="Search name or email" value={query.search} onChange={event => setQuery(current => ({ ...current, search: event.target.value, page: 1 }))} /><select value={query.status} onChange={event => setQuery(current => ({ ...current, status: event.target.value, page: 1 }))}><option value="">All statuses</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="expired">Expired</option></select><select value={query.track} onChange={event => setQuery(current => ({ ...current, track: event.target.value, page: 1 }))}><option value="">All tracks</option><option value="personal">Personal</option><option value="newjoiner">New Joiner</option><option value="manager">Manager</option><option value="executive">Executive</option></select></div>
    {loader.loading ? <Spinner /> : <section className="admin-card"><DataTable columns={["Participant", "Track", "Status", "Progress", "Payment", "Last activity"]} rows={(loader.data?.items || []).map(item => [<><strong>{item.name}</strong><span>{item.email}</span></>, item.track, item.status, `${item.progress || 0}%`, item.paymentStatus || "—", dateTime(item.lastActivityAt)])} onRow={index => open(loader.data.items[index])} /><div className="admin-pagination"><button className="button" disabled={query.page <= 1} onClick={() => setQuery(current => ({ ...current, page: current.page - 1 }))}>Previous</button><span>Page {query.page} · {loader.data?.total || 0} records</span><button className="button" disabled={query.page * query.limit >= (loader.data?.total || 0)} onClick={() => setQuery(current => ({ ...current, page: current.page + 1 }))}>Next</button></div></section>}
    {selected && <div className="admin-drawer"><div className="admin-drawer__panel"><button className="admin-drawer__close" onClick={() => setSelected(null)}>×</button><h2>{selected.participant.name}</h2><p>{selected.participant.email}</p><div className="admin-header-actions"><button className="button" onClick={exportRecord}>Export</button><button className="button button--danger" onClick={anonymise}>Anonymise</button></div><h3>Assessments</h3><DataTable columns={["Track", "Status", "Progress", "Completed"]} rows={(selected.sessions || []).map(item => [item.track, item.status, `${item.completion_percentage}%`, dateTime(item.completed_at)])} /><h3>Answers</h3><DataTable columns={["Question", "Answer", "Note"]} rows={(selected.answers || []).map(item => [item.questionText || item.question_position, item.answer_value, item.note || "—"])} /><h3>Reports</h3><DataTable columns={["Status", "Views", "Created"]} rows={(selected.reports || []).map(item => [item.is_unlocked ? "Full" : "Lite", item.view_count, dateTime(item.created_at)])} /><h3>Payments</h3><DataTable columns={["Status", "Amount", "Date"]} rows={(selected.payments || []).map(item => [item.status, money(item.amount, item.currency), dateTime(item.created_at)])} /><h3>Email history</h3><DataTable columns={["Template", "Status", "Date"]} rows={(selected.emails || []).map(item => [item.template_key, item.status, dateTime(item.created_at)])} /></div></div>}
  </>;
}

function TrackSettings({ item, onSaved }) {
  const [form, setForm] = React.useState({ publicTitle: `Growth Alignment: ${item.trackName}`, shortTitle: item.trackName, audienceLabel: "", durationMin: Number(item.estimatedMinutesMin || 15), durationMax: Number(item.estimatedMinutesMax || 15), averageSecondsPerQuestion: 18, averageSecondsPerParticipantField: 12, freeReportLabel: "Lite Report Free", paidReportLabel: "Full Report", freeReportReadMinutes: 3, paidReportReadMinutes: 12, showRemainingTime: true, showQuestionCount: true, showSectionCount: true, showAutosave: true, introductoryNote: "", lastReviewedDate: new Date().toISOString().slice(0, 10) });
  const save = () => api.saveTrackSettings(item.trackId, form).then(() => onSaved("Track timing and labels saved."));
  return <section className="admin-card editor-form"><h2>Track labels and timing</h2><div className="form-grid"><label>Public title<input value={form.publicTitle} onChange={event => setForm(current => ({ ...current, publicTitle: event.target.value }))} /></label><label>Short title<input value={form.shortTitle} onChange={event => setForm(current => ({ ...current, shortTitle: event.target.value }))} /></label><label>Audience label<input value={form.audienceLabel} onChange={event => setForm(current => ({ ...current, audienceLabel: event.target.value }))} /></label><label>Minimum minutes<input type="number" value={form.durationMin} onChange={event => setForm(current => ({ ...current, durationMin: Number(event.target.value) }))} /></label><label>Maximum minutes<input type="number" value={form.durationMax} onChange={event => setForm(current => ({ ...current, durationMax: Number(event.target.value) }))} /></label><label>Seconds per question<input type="number" value={form.averageSecondsPerQuestion} onChange={event => setForm(current => ({ ...current, averageSecondsPerQuestion: Number(event.target.value) }))} /></label><label>Free report label<input value={form.freeReportLabel} onChange={event => setForm(current => ({ ...current, freeReportLabel: event.target.value }))} /></label><label>Paid report label<input value={form.paidReportLabel} onChange={event => setForm(current => ({ ...current, paidReportLabel: event.target.value }))} /></label><label className="check-row"><input type="checkbox" checked={form.showRemainingTime} onChange={event => setForm(current => ({ ...current, showRemainingTime: event.target.checked }))} /> Show estimated time remaining</label><label className="check-row"><input type="checkbox" checked={form.showAutosave} onChange={event => setForm(current => ({ ...current, showAutosave: event.target.checked }))} /> Show autosave status</label></div><button className="button button--primary" onClick={save}>Save track settings</button></section>;
}

function AssessmentVersionEditor({ item, onClose, onSaved }) {
  const loader = useLoader(() => api.adminAssessmentVersion(item.versionId), [item.versionId]);
  const [questions, setQuestions] = React.useState([]);
  const [reports, setReports] = React.useState([]);
  const [questionPage, setQuestionPage] = React.useState(0);
  React.useEffect(() => { if (loader.data) { setQuestions(loader.data.questions || []); setReports(loader.data.reports || []); } }, [loader.data]);
  if (loader.loading) return <div className="admin-drawer"><div className="admin-drawer__panel"><Spinner /></div></div>;
  const draft = loader.data?.version?.status === "draft";
  const updateQuestionText = (index, value) => setQuestions(current => current.map((question, questionIndex) => questionIndex === index ? { ...question, question_text: value } : question));
  const saveQuestion = async index => {
    const question = questions[index];
    const confirmed = window.confirm("Save this text correction? Confirm that spelling or clarity is improved but the question meaning, scoring intent, position and answer interpretation remain unchanged.");
    if (!confirmed) return;
    const result = await api.saveQuestion(question.id, { questionText: question.question_text, confirmMeaningUnchanged: true });
    onSaved(result.unchanged ? `Question ${question.position} was unchanged.` : `Question ${question.position} text corrected. Identity and scoring remain locked.`);
  };
  const updateReport = (index, key, value) => setReports(current => current.map((report, reportIndex) => reportIndex === index ? { ...report, [key]: value } : report));
  const saveReport = async index => { const report = reports[index]; await api.saveReportTemplate(report.id, { profileName: report.profile_name, minScore: Number(report.min_score), maxScore: Number(report.max_score), freeContent: typeof report.free_content_json === "string" ? JSON.parse(report.free_content_json) : report.free_content_json, paidContent: typeof report.paid_content_json === "string" ? JSON.parse(report.paid_content_json) : report.paid_content_json }); onSaved(`${report.profile_name} report content saved.`); };
  const visible = questions.slice(questionPage * 10, questionPage * 10 + 10);
  return <div className="admin-drawer"><div className="admin-drawer__panel admin-drawer__panel--wide"><button className="admin-drawer__close" onClick={onClose}>×</button><p className="eyebrow">{item.trackName}</p><h2>Version {item.versionNumber}</h2>
    <Notice>{draft ? "Text correction only. You may improve spelling, grammar or clarity, but the question must remain the same. Position, section, stable identity, required/active state and scoring direction are locked. Published reports and existing sessions retain their original snapshots." : "Published and archived versions are immutable. Clone the version to prepare reviewed text corrections."}</Notice>
    <TrackSettings item={item} onSaved={onSaved} />
    <section className="admin-card"><div className="card-heading"><div><h2>Questions</h2><small>Do not replace a question or change its meaning. A material change requires a separately reviewed assessment version.</small></div><span>{questions.length} total</span></div>{visible.map((question, localIndex) => { const index = questionPage * 10 + localIndex; const scoring = question.scoring_direction === "K" ? "Reverse scored" : "Head / direct"; return <article className="question-editor" key={question.id}><div className="question-editor__meta"><strong>Question {question.position}</strong><span>{scoring} · Required · Active · Identity locked</span></div><textarea disabled={!draft} value={question.question_text} onChange={event => updateQuestionText(index, event.target.value)} /><div className="table-actions"><small>Allowed: spelling, grammar and clarity only. Meaning and scoring must remain unchanged.</small>{draft && <button onClick={() => saveQuestion(index)}>Save text correction</button>}</div></article>; })}<div className="admin-pagination"><button className="button" disabled={questionPage === 0} onClick={() => setQuestionPage(page => page - 1)}>Previous 10</button><span>Questions {questionPage * 10 + 1}–{Math.min(questionPage * 10 + 10, questions.length)}</span><button className="button" disabled={(questionPage + 1) * 10 >= questions.length} onClick={() => setQuestionPage(page => page + 1)}>Next 10</button></div></section>
    <section className="admin-card"><div className="card-heading"><h2>Free and paid report content</h2></div>{reports.map((report, index) => <article className="report-template-editor" key={report.id}><div className="form-grid"><label>Profile name<input disabled={!draft} value={report.profile_name} onChange={event => updateReport(index, "profile_name", event.target.value)} /></label><label>Minimum score<input disabled={!draft} type="number" value={report.min_score} onChange={event => updateReport(index, "min_score", Number(event.target.value))} /></label><label>Maximum score<input disabled={!draft} type="number" value={report.max_score} onChange={event => updateReport(index, "max_score", Number(event.target.value))} /></label></div><JsonEditor label="Lite report JSON" value={typeof report.free_content_json === "string" ? JSON.parse(report.free_content_json) : report.free_content_json} onChange={value => updateReport(index, "free_content_json", value)} /><JsonEditor label="Full report JSON" value={typeof report.paid_content_json === "string" ? JSON.parse(report.paid_content_json) : report.paid_content_json} onChange={value => updateReport(index, "paid_content_json", value)} />{draft && <button className="button" onClick={() => saveReport(index)}>Save report content</button>}</article>)}</section>
  </div></div>;
}

export function AssessmentsPage() {
  const loader = useLoader(() => api.adminAssessments(), []);
  const [notice, setNotice] = React.useState("");
  const [selected, setSelected] = React.useState(null);
  const clone = async item => { const versionNumber = prompt("New version number", "1.1.0"); if (!versionNumber) return; const changeSummary = prompt("Change summary", "Text corrections for review; question meaning and scoring unchanged") || "Draft copy"; await api.cloneAssessment(item.versionId, { versionNumber, changeSummary }); setNotice("Draft version created. Only text corrections are permitted in the question editor."); loader.refresh(); };
  const publish = async item => { if (!confirm(`Publish ${item.trackName} ${item.versionNumber}? The prior published version will be archived.`)) return; try { await api.publishAssessment(item.versionId); setNotice("Assessment version published."); loader.refresh(); } catch (error) { setNotice(error.message); } };
  return <><PageHeader title="Assessments" actions={<button className="button" onClick={loader.refresh}>Refresh</button>} /><Notice>{notice}</Notice><Notice type="error">{loader.error}</Notice>{loader.loading ? <Spinner /> : <section className="admin-card"><DataTable columns={["Track", "Version", "Status", "Questions", "Sections", "Actions"]} rows={(loader.data?.items || []).map(item => [item.trackName, item.versionNumber, <span className={`status status--${item.status}`}>{item.status}</span>, item.questionCount, item.sectionCount, <div className="table-actions"><button onClick={event => { event.stopPropagation(); setSelected(item); }}>Open</button><button onClick={event => { event.stopPropagation(); clone(item); }}>Clone</button>{item.status === "draft" && <button onClick={event => { event.stopPropagation(); publish(item); }}>Publish</button>}</div>])} /></section>}{selected && <AssessmentVersionEditor item={selected} onClose={() => setSelected(null)} onSaved={setNotice} />}</>;
}

export function ContentPage() {
  const loader = useLoader(() => api.adminContent(), []);
  const [selected, setSelected] = React.useState("version");
  const [content, setContent] = React.useState({});
  const [notice, setNotice] = React.useState("");
  React.useEffect(() => { if (loader.data?.items) setContent(loader.data.items); }, [loader.data]);
  const item = content[selected];
  const update = (key, value) => setContent(current => ({ ...current, [selected]: { ...current[selected], [key]: value } }));
  const upload = async event => { const file = event.target.files?.[0]; if (!file) return; const media = await api.uploadMedia(file, { altText: item.alt || "", focalX: 52, focalY: 50 }); update("image", media.url); update("desktopMediaId", media.id); setNotice("Image uploaded. Save the stage to activate the reference."); };
  const save = async () => { const focal = String(item.focalPoint || "50% 50%").split(" ").map(value => Number.parseFloat(value)); await api.saveContentStage(selected, { ...item, focalX: focal[0] || 50, focalY: focal[1] || 50 }); setNotice("Stage content saved."); };
  if (loader.loading || !item) return <Spinner />;
  return <><PageHeader eyebrow="Experience" title="Stage content" actions={<button className="button button--primary" onClick={save}>Save stage</button>} /><Notice>{notice}</Notice><Notice type="error">{loader.error}</Notice><div className="content-editor"><aside className="stage-list">{Object.entries(content).map(([key, stage]) => <button className={key === selected ? "active" : ""} key={key} onClick={() => setSelected(key)}><img src={stage.image} alt="" /><span>{key.replaceAll("-", " ")}<small>{stage.active ? "Active" : "Inactive"}</small></span></button>)}</aside><section className="admin-card editor-form"><div className="editor-preview" style={{ backgroundImage: `linear-gradient(rgba(24,20,15,.${item.overlay}),rgba(24,20,15,.${item.overlay})),url(${item.image})`, backgroundPosition: item.focalPoint }}><BrandLogo /><h2>{item.headline}</h2><p>{item.supporting}</p></div><div className="form-grid"><label>Desktop image<input type="file" accept="image/png,image/jpeg,image/webp,image/avif,image/svg+xml" onChange={upload} /></label><label>Headline<textarea value={item.headline || ""} onChange={event => update("headline", event.target.value)} /></label><label>Supporting text<textarea value={item.supporting || ""} onChange={event => update("supporting", event.target.value)} /></label><label>Image alt text<input value={item.alt || ""} onChange={event => update("alt", event.target.value)} /></label><label>Focal point<select value={item.focalPoint || "50% 50%"} onChange={event => update("focalPoint", event.target.value)}><option>40% 50%</option><option>50% 50%</option><option>52% 50%</option><option>60% 50%</option></select></label><label>Overlay strength <output>{item.overlay}%</output><input type="range" min="20" max="85" value={item.overlay || 40} onChange={event => update("overlay", Number(event.target.value))} /></label><label className="check-row"><input type="checkbox" checked={Boolean(item.active)} onChange={event => update("active", event.target.checked)} /> Active stage</label></div></section></div></>;
}

const brandFields = [
  ["canvas", "Canvas colour", "color"], ["surface", "Surface colour", "color"],
  ["textPrimary", "Primary text", "color"], ["textMuted", "Muted text", "color"],
  ["border", "Border colour", "color"], ["cta", "Primary CTA", "color"],
  ["ctaHover", "CTA hover", "color"], ["heart", "Heart colour", "color"],
  ["head", "Head colour", "color"], ["accent", "Accent / gold", "color"], ["navy", "Admin navy", "color"],
  ["questionnaireCopy", "Questionnaire body text", "color"], ["questionnaireLabel", "Questionnaire labels", "color"],
  ["inputSurface", "Input background", "color"], ["inputText", "Input text", "color"],
  ["optionSurface", "Answer option background", "color"], ["optionText", "Answer option text", "color"],
  ["selectedSurface", "Selected answer background", "color"], ["selectedText", "Selected answer text", "color"],
  ["progress", "Progress indicator", "color"], ["headingFont", "Heading font stack", "text"],
  ["bodyFont", "Body font stack", "text"], ["baseFontSize", "Base font size", "number"],
  ["pageTitleSize", "Page title size", "number"], ["bodyTextSize", "Body copy size", "number"],
  ["questionTextSize", "Question text size", "number"], ["optionTextSize", "Answer option size", "number"],
  ["fieldLabelSize", "Field label size", "number"], ["fieldTextSize", "Input text size", "number"],
  ["metaTextSize", "Meta / progress size", "number"], ["visualTitleSize", "Left-panel title size", "number"],
  ["visualBodySize", "Left-panel supporting size", "number"], ["contentMaxWidth", "Landing / introduction width", "number"],
  ["intakeMaxWidth", "Participant form width", "number"], ["questionMaxWidth", "Questionnaire width", "number"],
  ["contentGutter", "Desktop content gutter", "number"], ["cardRadius", "Card radius", "number"],
  ["buttonRadius", "Button / input radius", "number"],
];

export function BrandingPage() {
  const loader = useLoader(() => api.adminBranding(), []);
  const [draft, setDraft] = React.useState(null);
  const [draftId, setDraftId] = React.useState(null);
  const [notice, setNotice] = React.useState("");
  React.useEffect(() => { if (loader.data) { setDraft(loader.data.draft || loader.data.published); setDraftId(loader.data.draftId); } }, [loader.data]);
  if (loader.loading || !draft) return <Spinner />;
  const update = (key, value) => setDraft(current => ({ ...current, [key]: value }));
  const uploadAsset = key => async event => { const file = event.target.files?.[0]; if (!file) return; const media = await api.uploadMedia(file, { altText: key.toLowerCase().includes("logo") ? "Atom Global Consulting" : "Growth Alignment banner" }); update(key, media.url); setNotice("Asset uploaded. Save and publish the branding draft to activate it."); };
  const save = async () => { const result = await api.saveBrandingDraft(draft); setDraftId(result.draftId); setNotice("Branding draft saved."); };
  const publish = async () => { const id = draftId || (await api.saveBrandingDraft(draft)).draftId; await api.publishBranding(id); setNotice("Branding published. Participant pages, admin, emails and reports will use the new settings."); loader.refresh(); };
  const restore = () => { setDraft({ ...defaultConfiguration.branding }); setNotice("Defaults restored in the editor. Publish only after reviewing the preview and contrast."); };
  return <><PageHeader title="Branding" actions={<><button className="button" onClick={restore}>Restore defaults</button><button className="button" onClick={save}>Save draft</button><button className="button button--primary" onClick={publish}>Publish</button></>} /><Notice>{notice}</Notice><Notice type="error">{loader.error}</Notice><div className="branding-layout"><section className="admin-card editor-form"><h2>Theme and questionnaire system</h2><p className="admin-help">Controls apply to landing, introductions, participant form, questions, answer options, email frame and report styling. Branding never edits assessment wording, scoring or report profile logic.</p><div className="form-grid">{brandFields.map(([key, label, type]) => <label key={key}>{label}<input type={type} value={draft[key] ?? ""} onChange={event => update(key, type === "number" ? Number(event.target.value) : event.target.value)} /></label>)}</div><h2>Brand assets</h2><div className="form-grid"><label>Public logo<input type="file" accept="image/*" onChange={uploadAsset("logoUrl")} /><small>{draft.logoUrl}</small></label><label>Banner image<input type="file" accept="image/*" onChange={uploadAsset("bannerUrl")} /><small>{draft.bannerUrl || "Not set"}</small></label><label>Email logo<input type="file" accept="image/*" onChange={uploadAsset("emailLogoUrl")} /><small>{draft.emailLogoUrl}</small></label><label>Report logo<input type="file" accept="image/*" onChange={uploadAsset("reportLogoUrl")} /><small>{draft.reportLogoUrl}</small></label><label>Favicon<input type="file" accept="image/png,image/svg+xml,image/x-icon" onChange={uploadAsset("faviconUrl")} /><small>{draft.faviconUrl}</small></label></div></section><aside className="branding-preview" style={{ "--preview-canvas": draft.canvas, "--preview-surface": draft.surface, "--preview-ink": draft.textPrimary, "--preview-muted": draft.textMuted, "--preview-border": draft.border, "--preview-cta": draft.cta, "--preview-heading": draft.headingFont, "--preview-body": draft.bodyFont }}><img src={draft.logoUrl} alt="Atom Global Consulting" /><p>HEAD–HEART ALIGNMENT · LIVE PREVIEW</p><h2>Pause. Reflect. Choose wisely.</h2><span>Calm, reflective and consistent across participant, admin, email and report experiences.</span><button>Continue</button></aside></div></>;
}
